//! Chat message models.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use strum::{Display, EnumString};

/// Message role enum.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Display, EnumString)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
pub enum Role {
    User,
    Assistant,
    System,
}

/// Provenance kind for tracking message origins.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Display, EnumString)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum ProvenanceKind {
    /// Message from a real user via a channel.
    ExternalUser,
    /// Message forwarded from another session.
    InterSession,
    /// Message generated by the system itself.
    InternalSystem,
}

/// Tracks the origin of a message to prevent loops and maintain context.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputProvenance {
    pub kind: ProvenanceKind,
    /// Channel the message originated from.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_channel: Option<String>,
    /// Session ID if forwarded from another session.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_session_id: Option<String>,
    #[serde(default = "Utc::now", with = "crate::datetime_compat")]
    pub timestamp: DateTime<Utc>,
}

/// Tool call information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    pub parameters: HashMap<String, serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    /// Concise 1-2 line summary for LLM context.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_summary: Option<String>,
    #[serde(default = "Utc::now", with = "crate::datetime_compat")]
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub approved: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Nested tool calls for subagent tools.
    #[serde(default)]
    pub nested_tool_calls: Vec<ToolCall>,
}

/// Represents a single message in the conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    pub content: String,
    #[serde(default = "Utc::now", with = "crate::datetime_compat")]
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub metadata: HashMap<String, serde_json::Value>,
    #[serde(default)]
    pub tool_calls: Vec<ToolCall>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokens: Option<u64>,

    // Fields for complete session persistence
    /// Thinking/reasoning used for this response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_trace: Option<String>,
    /// Native model reasoning (o1/o3).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,
    /// Token usage stats (may contain nested dicts).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_usage: Option<HashMap<String, serde_json::Value>>,

    /// Input provenance tracking (multi-channel architecture).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<InputProvenance>,
}

impl ChatMessage {
    /// Estimate token count (rough approximation).
    pub fn token_estimate(&self) -> u64 {
        if let Some(tokens) = self.tokens {
            return tokens;
        }
        Self::compute_token_estimate(&self.content, &self.tool_calls)
    }

    /// Estimate token count and cache the result in `self.tokens`.
    ///
    /// On first call (when `tokens` is `None`), computes the estimate and
    /// stores it so subsequent calls skip recomputation.  Returns the
    /// (possibly newly cached) value.
    pub fn cache_token_estimate(&mut self) -> u64 {
        if let Some(tokens) = self.tokens {
            return tokens;
        }
        let estimate = Self::compute_token_estimate(&self.content, &self.tool_calls);
        self.tokens = Some(estimate);
        estimate
    }

    /// Compute token estimate from content and tool calls (no caching).
    fn compute_token_estimate(content: &str, tool_calls: &[ToolCall]) -> u64 {
        // Rough estimate: ~4 chars per token
        let content_tokens = content.len() as u64 / 4;
        let tool_tokens: u64 = tool_calls
            .iter()
            .map(|tc| {
                let params_str = serde_json::to_string(&tc.parameters).unwrap_or_default();
                params_str.len() as u64 / 4
            })
            .sum();
        content_tokens + tool_tokens
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_role_serialization() {
        let role = Role::User;
        let json = serde_json::to_string(&role).unwrap();
        assert_eq!(json, "\"user\"");

        let deserialized: Role = serde_json::from_str("\"assistant\"").unwrap();
        assert_eq!(deserialized, Role::Assistant);
    }

    #[test]
    fn test_chat_message_roundtrip() {
        let msg = ChatMessage {
            role: Role::User,
            content: "Hello world".to_string(),
            timestamp: Utc::now(),
            metadata: HashMap::new(),
            tool_calls: vec![],
            tokens: Some(3),
            thinking_trace: None,
            reasoning_content: None,
            token_usage: None,
            provenance: None,
        };

        let json = serde_json::to_string(&msg).unwrap();
        let deserialized: ChatMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.role, Role::User);
        assert_eq!(deserialized.content, "Hello world");
        assert_eq!(deserialized.tokens, Some(3));
    }

    #[test]
    fn test_tool_call_with_nested() {
        let nested = ToolCall {
            id: "nested-1".to_string(),
            name: "read_file".to_string(),
            parameters: HashMap::new(),
            result: Some(serde_json::Value::String("file contents".to_string())),
            result_summary: Some("Read 10 lines".to_string()),
            timestamp: Utc::now(),
            approved: true,
            error: None,
            nested_tool_calls: vec![],
        };

        let tc = ToolCall {
            id: "tc-1".to_string(),
            name: "agent".to_string(),
            parameters: HashMap::new(),
            result: Some(serde_json::Value::String("done".to_string())),
            result_summary: None,
            timestamp: Utc::now(),
            approved: true,
            error: None,
            nested_tool_calls: vec![nested],
        };

        let json = serde_json::to_string(&tc).unwrap();
        let deserialized: ToolCall = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.nested_tool_calls.len(), 1);
        assert_eq!(deserialized.nested_tool_calls[0].name, "read_file");
    }

    #[test]
    fn test_token_estimate() {
        let msg = ChatMessage {
            role: Role::Assistant,
            content: "a".repeat(400),
            timestamp: Utc::now(),
            metadata: HashMap::new(),
            tool_calls: vec![],
            tokens: None,
            thinking_trace: None,
            reasoning_content: None,
            token_usage: None,
            provenance: None,
        };
        assert_eq!(msg.token_estimate(), 100);

        // With explicit tokens set
        let msg2 = ChatMessage {
            tokens: Some(42),
            ..msg
        };
        assert_eq!(msg2.token_estimate(), 42);
    }

    #[test]
    fn test_cache_token_estimate() {
        let mut msg = ChatMessage {
            role: Role::Assistant,
            content: "a".repeat(400),
            timestamp: Utc::now(),
            metadata: HashMap::new(),
            tool_calls: vec![],
            tokens: None,
            thinking_trace: None,
            reasoning_content: None,
            token_usage: None,
            provenance: None,
        };
        assert!(msg.tokens.is_none());
        let estimate = msg.cache_token_estimate();
        assert_eq!(estimate, 100);
        // Now tokens should be cached
        assert_eq!(msg.tokens, Some(100));
        // Subsequent calls return the cached value
        assert_eq!(msg.cache_token_estimate(), 100);
    }

    #[test]
    fn test_provenance_serialization() {
        let prov = InputProvenance {
            kind: ProvenanceKind::ExternalUser,
            source_channel: Some("telegram".to_string()),
            source_session_id: None,
            timestamp: Utc::now(),
        };

        let json = serde_json::to_string(&prov).unwrap();
        assert!(json.contains("\"external_user\""));
        assert!(json.contains("\"telegram\""));
        // source_session_id should be skipped (None)
        assert!(!json.contains("source_session_id"));
    }
}
