// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AskUserRequiredPayload = { request_id: string, question: string, options: Array<string>, default: string | null, session_id: string | null, };
