// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalRequiredPayload } from "./ApprovalRequiredPayload";
import type { AskUserRequiredPayload } from "./AskUserRequiredPayload";
import type { ErrorPayload } from "./ErrorPayload";
import type { MessageChunkPayload } from "./MessageChunkPayload";
import type { MessageCompletePayload } from "./MessageCompletePayload";
import type { MessageStartPayload } from "./MessageStartPayload";
import type { NestedToolCallPayload } from "./NestedToolCallPayload";
import type { NestedToolResultPayload } from "./NestedToolResultPayload";
import type { PlanApprovalRequiredPayload } from "./PlanApprovalRequiredPayload";
import type { ProgressPayload } from "./ProgressPayload";
import type { SessionActivityPayload } from "./SessionActivityPayload";
import type { StatusUpdatePayload } from "./StatusUpdatePayload";
import type { SubagentCompletedPayload } from "./SubagentCompletedPayload";
import type { SubagentStartedPayload } from "./SubagentStartedPayload";
import type { ThinkingBlockPayload } from "./ThinkingBlockPayload";
import type { ToolCallPayload } from "./ToolCallPayload";
import type { ToolResultPayload } from "./ToolResultPayload";

/**
 * A frontend event that both the TUI and Web UI can render.
 *
 * Serialized as a tagged union: `{"type": "MessageChunk", "data": {...}}`.
 */
export type FrontendEvent = { "type": "MessageStart", "data": MessageStartPayload } | { "type": "MessageChunk", "data": MessageChunkPayload } | { "type": "MessageComplete", "data": MessageCompletePayload } | { "type": "ToolCall", "data": ToolCallPayload } | { "type": "ToolResult", "data": ToolResultPayload } | { "type": "ThinkingBlock", "data": ThinkingBlockPayload } | { "type": "SubagentStarted", "data": SubagentStartedPayload } | { "type": "SubagentCompleted", "data": SubagentCompletedPayload } | { "type": "NestedToolCall", "data": NestedToolCallPayload } | { "type": "NestedToolResult", "data": NestedToolResultPayload } | { "type": "StatusUpdate", "data": StatusUpdatePayload } | { "type": "Progress", "data": ProgressPayload } | { "type": "ApprovalRequired", "data": ApprovalRequiredPayload } | { "type": "AskUserRequired", "data": AskUserRequiredPayload } | { "type": "PlanApprovalRequired", "data": PlanApprovalRequiredPayload } | { "type": "SessionActivity", "data": SessionActivityPayload } | { "type": "Error", "data": ErrorPayload };
