// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NestedToolResultPayload = { subagent_id: string, tool_name: string, tool_id: string, success: boolean, depth: number, };
