// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanApprovalRequiredPayload = { request_id: string, plan_content: string, session_id: string | null, };
