// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChangesPayload } from "./FileChangesPayload";
import type { TodoItemPayload } from "./TodoItemPayload";

export type StatusUpdatePayload = { session_id: string, model: string | null, provider: string | null, input_tokens: bigint | null, output_tokens: bigint | null, context_usage_pct: number | null, session_cost_usd: number | null, git_branch: string | null, autonomy_level: string | null, thinking_level: string | null, file_changes: FileChangesPayload | null, todos: Array<TodoItemPayload> | null, };
