// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentStartedPayload = { subagent_id: string, agent_type: string, description: string, tool_call_id: string | null, session_id: string | null, };
