// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentCompletedPayload = { subagent_id: string, success: boolean, result_summary: string, tool_call_count: number, shallow_warning: string | null, session_id: string | null, };
