// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThinkingBlockPayload = { session_id: string, content: string, block_start: boolean, level: string | null, };
