// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoChildPayload } from "./TodoChildPayload";

export type TodoItemPayload = { id: string, title: string, status: string, active_form: string | null, children: Array<TodoChildPayload>, };
