// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoItemPayload } from "./TodoItemPayload";

export type ToolResultPayload = { session_id: string, tool_id: string, tool_name: string, output: string, success: boolean, 
/**
 * Optional todo state included when tool is a todo-related tool.
 */
todos: Array<TodoItemPayload> | null, };
