// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolCallPayload = { session_id: string, tool_id: string, tool_name: string, arguments: Record<string, any>, };
